/**
 * ambianic-functions-collection
 * A postman collection documenting the Netlify cloud functions created for use within Ambianic-PWA
 *
 * The version of the OpenAPI document: a7b6cde1-7435-479a-bd1a-20ab61f9ae08
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Default service.
* @module api/DefaultApi
* @version a7b6cde1-7435-479a-bd1a-20ab61f9ae08
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteSubscription operation.
     * @callback module:api/DefaultApi~deleteSubscriptionCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an Ambianic's user subscription
     * Delete a user's subscription on Stripe, either active or expired.
     * @param {String} subscriptionId ID for the user's subscription to be deleted
     * @param {String} accessControlAllowOrigin 
     * @param {String} accessControlAllowHeaders 
     * @param {String} contentType 
     * @param {module:api/DefaultApi~deleteSubscriptionCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteSubscription(subscriptionId, accessControlAllowOrigin, accessControlAllowHeaders, contentType, callback) {
      let postBody = null;
      // verify the required parameter 'subscriptionId' is set
      if (subscriptionId === undefined || subscriptionId === null) {
        throw new Error("Missing the required parameter 'subscriptionId' when calling deleteSubscription");
      }
      // verify the required parameter 'accessControlAllowOrigin' is set
      if (accessControlAllowOrigin === undefined || accessControlAllowOrigin === null) {
        throw new Error("Missing the required parameter 'accessControlAllowOrigin' when calling deleteSubscription");
      }
      // verify the required parameter 'accessControlAllowHeaders' is set
      if (accessControlAllowHeaders === undefined || accessControlAllowHeaders === null) {
        throw new Error("Missing the required parameter 'accessControlAllowHeaders' when calling deleteSubscription");
      }
      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling deleteSubscription");
      }

      let pathParams = {
      };
      let queryParams = {
        'subscriptionId': subscriptionId
      };
      let headerParams = {
        'Access-Control-Allow-Origin': accessControlAllowOrigin,
        'Access-Control-Allow-Headers': accessControlAllowHeaders,
        'Content-Type': contentType
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/subscription', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubscriptionData operation.
     * @callback module:api/DefaultApi~getSubscriptionDataCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a user's subscription data
     * Retrieve a subscribed customer's data from Stripe
     * @param {String} userStripeId Id for the customer created on Stripe
     * @param {String} userSubscriptionId Id for the user's subscription with Ambianic
     * @param {String} accessControlAllowOrigin 
     * @param {String} accessControlAllowHeaders 
     * @param {String} contentType 
     * @param {module:api/DefaultApi~getSubscriptionDataCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getSubscriptionData(userStripeId, userSubscriptionId, accessControlAllowOrigin, accessControlAllowHeaders, contentType, callback) {
      let postBody = null;
      // verify the required parameter 'userStripeId' is set
      if (userStripeId === undefined || userStripeId === null) {
        throw new Error("Missing the required parameter 'userStripeId' when calling getSubscriptionData");
      }
      // verify the required parameter 'userSubscriptionId' is set
      if (userSubscriptionId === undefined || userSubscriptionId === null) {
        throw new Error("Missing the required parameter 'userSubscriptionId' when calling getSubscriptionData");
      }
      // verify the required parameter 'accessControlAllowOrigin' is set
      if (accessControlAllowOrigin === undefined || accessControlAllowOrigin === null) {
        throw new Error("Missing the required parameter 'accessControlAllowOrigin' when calling getSubscriptionData");
      }
      // verify the required parameter 'accessControlAllowHeaders' is set
      if (accessControlAllowHeaders === undefined || accessControlAllowHeaders === null) {
        throw new Error("Missing the required parameter 'accessControlAllowHeaders' when calling getSubscriptionData");
      }
      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling getSubscriptionData");
      }

      let pathParams = {
      };
      let queryParams = {
        'userStripeId': userStripeId,
        'userSubscriptionId': userSubscriptionId
      };
      let headerParams = {
        'Access-Control-Allow-Origin': accessControlAllowOrigin,
        'Access-Control-Allow-Headers': accessControlAllowHeaders,
        'Content-Type': contentType
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/subscription', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the sendNotification operation.
     * @callback module:api/DefaultApi~sendNotificationCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send an event detection notification
     * An endpoint to send notifications about detected objects to a premium ambianic subscriber from a running edge device, delivered from the Cloud API.
     * @param {String} userId 
     * @param {String} notification Notification object containing detected event details from running ambianic edge device
     * @param {String} accessControlAllowOrigin 
     * @param {module:api/DefaultApi~sendNotificationCallback} callback The callback function, accepting three arguments: error, data, response
     */
    sendNotification(userId, notification, accessControlAllowOrigin, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling sendNotification");
      }
      // verify the required parameter 'notification' is set
      if (notification === undefined || notification === null) {
        throw new Error("Missing the required parameter 'notification' when calling sendNotification");
      }
      // verify the required parameter 'accessControlAllowOrigin' is set
      if (accessControlAllowOrigin === undefined || accessControlAllowOrigin === null) {
        throw new Error("Missing the required parameter 'accessControlAllowOrigin' when calling sendNotification");
      }

      let pathParams = {
      };
      let queryParams = {
        'userId': userId,
        'notification': notification
      };
      let headerParams = {
        'Access-Control-Allow-Origin': accessControlAllowOrigin
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/notification', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the subscribeUser operation.
     * @callback module:api/DefaultApi~subscribeUserCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Subscribe Ambianic user to premium notification
     * Create a new stripe user and a subscription
     * @param {String} _number 16 digit Number on the credit card supplied
     * @param {String} cvc Cvc number behind credit card
     * @param {String} expMonth 2 digit expected credit card expiry month. 
     * @param {String} expYear 4 digit expected credit card expiry year. 
     * @param {String} email Subscriber's email address
     * @param {String} accessControlAllowOrigin 
     * @param {String} accessControlAllowHeaders 
     * @param {String} contentType 
     * @param {module:api/DefaultApi~subscribeUserCallback} callback The callback function, accepting three arguments: error, data, response
     */
    subscribeUser(_number, cvc, expMonth, expYear, email, accessControlAllowOrigin, accessControlAllowHeaders, contentType, callback) {
      let postBody = null;
      // verify the required parameter '_number' is set
      if (_number === undefined || _number === null) {
        throw new Error("Missing the required parameter '_number' when calling subscribeUser");
      }
      // verify the required parameter 'cvc' is set
      if (cvc === undefined || cvc === null) {
        throw new Error("Missing the required parameter 'cvc' when calling subscribeUser");
      }
      // verify the required parameter 'expMonth' is set
      if (expMonth === undefined || expMonth === null) {
        throw new Error("Missing the required parameter 'expMonth' when calling subscribeUser");
      }
      // verify the required parameter 'expYear' is set
      if (expYear === undefined || expYear === null) {
        throw new Error("Missing the required parameter 'expYear' when calling subscribeUser");
      }
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling subscribeUser");
      }
      // verify the required parameter 'accessControlAllowOrigin' is set
      if (accessControlAllowOrigin === undefined || accessControlAllowOrigin === null) {
        throw new Error("Missing the required parameter 'accessControlAllowOrigin' when calling subscribeUser");
      }
      // verify the required parameter 'accessControlAllowHeaders' is set
      if (accessControlAllowHeaders === undefined || accessControlAllowHeaders === null) {
        throw new Error("Missing the required parameter 'accessControlAllowHeaders' when calling subscribeUser");
      }
      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling subscribeUser");
      }

      let pathParams = {
      };
      let queryParams = {
        'number': _number,
        'cvc': cvc,
        'exp_month': expMonth,
        'exp_year': expYear,
        'email': email
      };
      let headerParams = {
        'Access-Control-Allow-Origin': accessControlAllowOrigin,
        'Access-Control-Allow-Headers': accessControlAllowHeaders,
        'Content-Type': contentType
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/subscribe', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
