/**
 * Ambianic Serverless functions API Definition
 * An API Definition for Ambianic Serverless functions created using Swagger
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmbianicServerlessFunctionsApiDefinition);
  }
}(this, function(expect, AmbianicServerlessFunctionsApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmbianicServerlessFunctionsApiDefinition.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('netlifyFunctionsCustomersGet', function() {
      it('should call netlifyFunctionsCustomersGet successfully', function(done) {
        //uncomment below and update the code to test netlifyFunctionsCustomersGet
        //instance.netlifyFunctionsCustomersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriberPost', function() {
      it('should call subscriberPost successfully', function(done) {
        //uncomment below and update the code to test subscriberPost
        //instance.subscriberPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionDelete', function() {
      it('should call subscriptionDelete successfully', function(done) {
        //uncomment below and update the code to test subscriptionDelete
        //instance.subscriptionDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
