/**
 * ambianic-cloud-api-collection
 * This collection contains a specification for all API endpoints within Ambianic's Cloud API.
 *
 * The version of the OpenAPI document: 1x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmbianicCloudApiCollection);
  }
}(this, function(expect, AmbianicCloudApiCollection) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2004Product', function() {
    it('should create an instance of InlineResponse2004Product', function() {
      // uncomment below and update the code to test InlineResponse2004Product
      //var instane = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be.a(AmbianicCloudApiCollection.InlineResponse2004Product);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property livemode (base name: "livemode")', function() {
      // uncomment below and update the code to test the property livemode
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property _object (base name: "object")', function() {
      // uncomment below and update the code to test the property _object
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property packageDimensions (base name: "package_dimensions")', function() {
      // uncomment below and update the code to test the property packageDimensions
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property shippable (base name: "shippable")', function() {
      // uncomment below and update the code to test the property shippable
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property statementDescriptor (base name: "statement_descriptor")', function() {
      // uncomment below and update the code to test the property statementDescriptor
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property unitLabel (base name: "unit_label")', function() {
      // uncomment below and update the code to test the property unitLabel
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property updated (base name: "updated")', function() {
      // uncomment below and update the code to test the property updated
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new AmbianicCloudApiCollection.InlineResponse2004Product();
      //expect(instance).to.be();
    });

  });

}));
