name: Ambianic Functions API CI Test 

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install application dependencies
      run: npm install

    - name: Install Node JS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Newman dependency
      run: npm install --prefix tests/postman/

    - name: Start Netlify Dev for local function testing
      run:  npm run netlify-dev & sleep 10 && cd tests && node newman.js 
      env:
        STRIPE_TEST_KEY: sk_test_7LEesZrYrgDtyxsc6Hy5i0lS00GVFEbmqb
        ENDPOINT: http://localhost:5050

    - name: Run tests against deployed preview
      run:  cd tests && node newman.js 
      env:
        STRIPE_TEST_KEY: sk_test_7LEesZrYrgDtyxsc6Hy5i0lS00GVFEbmqb
        ENDPOINT: https://deploy-preview-${{github.event.number}}--ambianic-serverless.netlify.app/.netlify/functions
    
    - name: Generate OpenAPI specs
      run: |
        npm run generate-swagger && ./cleanup.sh
    
    - name: Create a static API documentation page from openapi specs
      run: npm run generate-docs

      # run this step only if its a push to the main branch
    - name: Publish static API documentation to Github Pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        personal_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        publish_dir: ./github-pages

    - name: Run the semantic-release
      run: npx semantic-release
    
    - name: Code Coverage Report
      uses: codecov/codecov-action@v1
      with:
        file: ./docs/coverage/coverage-final.json
        fail_ci_if_error: true 