name: Ambianic Functions API CI Test 

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout 
      uses: actions/checkout@v2
    
    - name: Install application dependencies
      run: npm install

    - name: Install Node JS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Newman dependency
      run: npm install --prefix tests/postman/

    - name: Run the API and Postman's tests
      run: |
        cd tests/postman/ && newman run *
      env:
        API_HOST: 0.0.0.0
        CI: true
     
    - name: Generate OpenAPI specs
      run: |
        npm run generate-swagger && ./cleanup.sh
    
    - name: Run the Openapi API tests
      run: |
        cd docs && sed -i 's/"version": "0.1"/"version": "1.0.0"/' package.json && npm install && npm test
      env:
        CI: true
    
    - name: Code Coverage Report
      uses: codecov/codecov-action@v1
      with:
        file: ./docs/coverage/coverage-final.json
        fail_ci_if_error: true 